apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
spec:
  storageClassName: rook-ceph-block # 위에서 만든 블록 스토리지 클래스
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi