apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: gitlab-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.219.200-192.168.219.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - gitlab-ip-pool
