apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx-svc","namespace":"default"},"spec":{"ports":[{"name":"tcp","port":80,"targetPort":80}],"selector":{"app":"nginx"},"type":"ClusterIP"}}
  creationTimestamp: "2025-09-01T12:41:37Z"
  name: nginx-svc
  namespace: default
  resourceVersion: "1024911"
  uid: 5ea4a15e-1171-4603-8234-fac14b213210
spec:
  clusterIP: 10.233.36.249
  clusterIPs:
  - 10.233.36.249
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
