apiVersion: v1
kind: Pod
metadata:
  name: nginx-19
  labels:
    app: nginx-19
spec:
  containers:
    - name: nginx-pod
      # image: nginx:1.19 # 존재하지 않는 이미지 일부러 생성
      image: nginx:1.19 # 수정
      ports:
        - containerPort: 80