apiVersion: v1
kind: Pod
metadata:
  name: mem-stress
  namespace: default
spec:
  containers:
  - name: stress
    image: polinux/stress:latest
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "6500M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "3Gi"
      limits:
        memory: "6Gi"
  restartPolicy: Always
